apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-backend-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-backend-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-backend-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql/postgres"
            - name: COINMARKETCAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secretkv
                  key: coinmarketcap_api_key
