apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-backend-app.fullname" . }}-ingress
spec:
  rules:
    - http:
        paths:
          - path: /delete
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-backend-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /populate
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-backend-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
